### ISSUE TITLE
PWA Capabilities on Android

### ISSUE THREAD

**Issue by stetro** [ihatecsv/TouchStadia-website#1]
Hey cool idea! Works great for me :)

I just had the idea to add a bit more functionality to the touch stadia website like a "copy to clipboard" button with`document.exec("copy")` or installing the page as progressive web app? If you like the idea I could give it a try :)

**Comment by ihatecsv** [comment]
Hi stetro! Thanks for making the first issue in the TouchStadia repo! I've made a new repo, the one this issue has been moved to, and you're welcome to make a pull request here if you'd like to make improvements!

I think a "Copy to clipboard" button is definitely desired functionality, feel free to make a PR!

**Comment by stetro** [comment]
Added a Copy to Clipboard Function in #2 and PWA capabilities in #3

**Comment by stetro** [comment]
#2 and #3 merged
